name: Atualização Diária do Robô de Futebol

on:
  schedule:
    - cron: '0 7 * * *' # Roda às 07:00 UTC (04:00 Horário de Brasília)
  workflow_dispatch: # Permite rodar o robô manualmente clicando no botão

jobs:
  rodar-ia:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Corrigido aqui de 'node-node' para 'node-version'

      - name: Instalar dependências
        run: npm install

      - name: Executar o Motor de Poisson
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node index.js